Header.js & Inbox.js Updated
CyberHoodie/bottlenose-mail pull request #18
Opened 2020-09-09 01:14 UTC by nickelliston

Updated header.js and inbox.js with bootstrap.  Used Jumbotron for Header.

## A picture tells a thousand words

## What was done
- Updated Header.js with Jumbotron using Bootstrap
- Formatted Inbox.js using Form
-

2020-09-09 03:21 UTC, frankolson requested changes

2020-09-09 03:21 UTC, frankolson commented on website/src/components/Header/Header.js
> +            <p className="lead" style={{ color: "black" }}>
This is more of a style preference, but I like to include spaces in between major HTML elements.
```suggestion
            </h1>
            
            <p className="lead" style={{ color: "black" }}>
```

2020-09-09 03:21 UTC, frankolson commented on website/src/components/Header/Header.js
> +            <br />
We should use margins instead of breaklines.

2020-09-09 03:21 UTC, frankolson commented on website/src/views/Inbox/Inbox.js
> +          <Form.Label style={{ color: "black" }}>Inbox</Form.Label>
We should use css classes instead of inline styles.

2020-09-20 23:27 UTC, nickelliston commented
Closing in favor of #19

2020-09-20 23:27 UTC, closed without merging